[build]
  command = "yarn && yarn build && lerna run setup"
  publish = "packages/graphiql-examples/cdn"

[context.monaco-test]
  publish = "packages/graphiql-examples/monaco-graphql-test/dist/bundle"
